language: node_js
node_js:
- lts/carbon
addons:
  postgresql: '9.5'
  chrome: stable
env:
- DJANGO_VERSION=2.1.2 DB=postgresql DISPLAY=:99.0 CHROME_BIN=/usr/bin/google-chrome
  DJANGO_HOST=http://127.0.0.1:8000/api
install:
- npm install
- pyenv global 3.6.3
- pip install --upgrade pip
- pip install -r requirements.txt
before_script:
- sh -e /etc/init.d/xvfb start
- psql -c "CREATE DATABASE outdoors_club_db"
- python src/django/manage.py migrate
- python src/django/manage.py createworker
script:
- coverage run --source='src/django/api/views/' --omit='src/django/api/views/PayPalView.py'
  src/django/manage.py test api
- coverage report --fail-under=70
- npm run-script lint
- npm test -- --single-run
before_install:
- openssl aes-256-cbc -K $encrypted_3b91031844f4_key -iv $encrypted_3b91031844f4_iv
  -in deploy_rsa.enc -out ~\/.ssh/deploy_rsa -d
