
language: node_js

node_js:
  - "lts/carbon"

addons:
  postgresql: "9.5"

env:
  - DJANGO_VERSION=2.1.2 DB=postgresql

install:
  - pyenv global 3.6.3
  - pip install -r requirements.txt
  - npm install

script:
  - cd src/django
  - python manage.py test
  - psql -c "CREATE DATABASE outdoors_club_db"
  - python manage.py migrate
  - python manage.py runserver &
  - cd ../../
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run-script lint
  - npm test -- --single-run