language: node_js
dist: trusty
node_js:
- lts/carbon
addons:
  postgresql: '9.5'
  chrome: stable
  ssh_known_hosts: 199.116.235.142
env:
- DJANGO_VERSION=2.1.2 DB=postgresql DISPLAY=:99.0 CHROME_BIN=/usr/bin/google-chrome
  DJANGO_HOST=http://127.0.0.1:8000/api
install:
- npm install
- pyenv global 3.6.3
- pip install --upgrade pip
- pip install -r requirements.txt
before_script:
- sh -e /etc/init.d/xvfb start
- psql -c "CREATE DATABASE outdoors_club_db"
- python src/django/manage.py migrate
- python src/django/manage.py createworker
script:
- echo "script"
# - coverage run --source='src/django/api/views/' --omit='src/django/api/views/PayPalView.py'
#   src/django/manage.py test api
# - coverage report --fail-under=70
# - npm run-script lint
# - npm test -- --single-run
before_deploy:
- openssl aes-256-cbc -K $encrypted_e8f9f979370e_key -iv $encrypted_e8f9f979370e_iv -in key_outdoors.pem.enc -out /tmp/key_outdoors -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/key_outdoors
- ssh-add /tmp/key_outdoors
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: ssh-encryption