matrix:
  include:
  - language: python
    python:
      - "3.5"
    services:
      - postgresql
    env:
      - DJANGO_VERSION=2.1.2 DB=postgresql
    install:
      - pip install -r requirements.txt
    before_script:
      - cd src/django
    script:
      - python3 manage.py test

  - language: node_js
    node_js:
      - "node"
    before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    script:
    - npm test -- --single-run