# Generated by Django 2.1.1 on 2018-10-05 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('conditionID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('ADEQUATE', 'Adequate'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], default='EXCELLENT', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('gearUUID', models.AutoField(primary_key=True, serialize=False)),
                ('gearID', models.CharField(max_length=6)),
                ('gearType', models.CharField(max_length=3)),
                ('available', models.BooleanField(default=True)),
                ('depositFee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GearCategory',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permissionID', models.AutoField(primary_key=True, serialize=False)),
                ('permissionType', models.CharField(choices=[('EDIT_BLACKLIST', 'Edit Blacklist'), ('EDIT_GEAR', 'Edit Gear'), ('EDIT_RESERVATION', 'Edit Reservation'), ('CANCELLED', 'Cancelled'), ('RENTED', 'Rented')], default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationID', models.AutoField(primary_key=True, serialize=False)),
                ('reservedBy', models.EmailField(max_length=254)),
                ('approvedBy', models.CharField(max_length=50)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled'), ('TAKEN', 'Taken'), ('RETURNED', 'Returned')], default='REQUESTED', max_length=20)),
                ('gearReserved', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Gear')),
            ],
        ),
        migrations.AddField(
            model_name='condition',
            name='gearID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Gear'),
        ),
    ]
