# Generated by Django 2.1.2 on 2018-11-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='statusDescription',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalgear',
            name='statusDescription',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
