# Generated by Django 2.1.1 on 2018-10-23 00:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionhistory',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='conditionhistory',
            name='gearID',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='gearID',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservationID',
        ),
        migrations.AddField(
            model_name='gear',
            name='condition',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='api.Condition'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='approvedBy',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='endDate',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='licenseAddress',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='licenseName',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='reservation',
            name='startDate',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('TAKEN', 'Taken'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='reservationID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.Reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ConditionHistory',
        ),
        migrations.DeleteModel(
            name='GearRequest',
        ),
    ]
