# Generated by Django 2.1.1 on 2018-11-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservariability',
            name='id',
        ),
        migrations.AlterField(
            model_name='uservariability',
            name='variable',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
