# Generated by Django 2.1.2 on 2018-10-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='conditionComments',
            field=models.CharField(blank=True, max_length=100),
        ),
        
    ]
