# Generated by Django 2.1.1 on 2018-10-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181022_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='checkedOut',
        ),
        migrations.AlterField(
            model_name='condition',
            name='condition',
            field=models.CharField(choices=[('EXCELLENT', 'Rentable'), ('FLAGGED', 'Flagged'), ('NEEDS REPAIR', 'Needs Repair'), ('DELETED', 'Deleted')], default=None, max_length=20),
        ),
    ]
