# Generated by Django 2.1.2 on 2018-11-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181101_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment',
            field=models.CharField(blank=True, max_length=19),
        ),
    ]
