# Generated by Django 2.1.2 on 2018-10-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181012_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='gearComment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
