# Generated by Django 2.1.1 on 2018-10-24 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181023_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='gear',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='api.Gear'),
        ),
    ]
