# Generated by Django 2.1.2 on 2018-11-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181106_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='id',
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
