# Generated by Django 2.1.2 on 2018-10-12 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gear_gearcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='conditionComments',
        ),
    ]
