# Generated by Django 2.1.2 on 2018-10-13 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_condition_conditioncomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='gearComment',
        ),
    ]
