# Generated by Django 2.1.2 on 2018-11-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181117_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.GearCategory'),
        ),
    ]
