# Generated by Django 2.1.2 on 2018-11-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181117_1238'),
        ('api', '0006_historicalgear_historicalreservation'),
    ]

    operations = [
    ]
